# Generated by Django 3.2.13 on 2022-05-26 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccountModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일시')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
                ('username', models.CharField(max_length=10, verbose_name='이름')),
                ('user_id', models.CharField(max_length=20, verbose_name='ID')),
                ('pw', models.CharField(max_length=20, verbose_name='비밀번호')),
                ('gmail_address', models.EmailField(max_length=254, unique=True, verbose_name='Gmail 주소')),
                ('email_address', models.EmailField(max_length=254, unique=True, verbose_name='email 주소')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
