# Generated by Django 3.2.13 on 2022-05-26 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20220526_1354'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermodel',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='usermodel',
            name='password',
        ),
        migrations.AddField(
            model_name='usermodel',
            name='name',
            field=models.CharField(default=None, max_length=10, unique=True, verbose_name='이름'),
            preserve_default=False,
        ),
    ]
