# Generated by Django 3.2.13 on 2022-05-26 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20220526_1433'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserModel',
        ),
    ]
