# Generated by Django 3.2.13 on 2022-06-07 08:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('todolists', '0004_auto_20220530_1727'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ToDoListModel',
            new_name='ToDoList',
        ),
        migrations.AlterField(
            model_name='todolist',
            name='created_by',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='todolist_writer', to=settings.AUTH_USER_MODEL, verbose_name='작성자'),
        ),
    ]
